### ISSUE TITLE
Seek for access to the annotation files of IsoGD dataset used in this paper

### ISSUE THREAD

**Issue by Zeng-Jia** [ZitongYu/3DCDC-NAS#1]
The **annotation files** of IsoGD dataset (for instance "**rgb_train_lst.txt**") used in this paper not found!
The official annotation file of IsoGD dataset has three columns and looks like this:
```
valid/001/M_00001.avi valid/001/K_00001.avi 109
valid/001/M_00002.avi valid/001/K_00002.avi 241
...
```
However, in your dataset parser codes like [Videodatasets](https://github.com/ZitongYu/3DCDC-NAS/blob/master/AutoGesture/Single_modality/Videodatasets.py), it seems that the columns are different from official annotation file.
```
def get_data_list_and_label(data_df, typ):
      T = 0  # if typ == 'M' else 1
      return [(lambda arr: ('/'.join(arr[T].split('/')[1:]), int(arr[1]), int(arr[2])))(i[:-1].split(' '))
              for i in open(data_df).readlines()]
```
Would you like to share your annotation files or provide a detailed explanation.
Looking forward to your reply! Thanks!

**Comment by Zeng-Jia** [comment]
I assume the second column of the annotation file is frame counts of videos.

**Comment by ZitongYu** [comment]
The preprocessed list is shared in the link below:
https://drive.google.com/drive/folders/14pddCQBvlj43pxJJENi8pqp9YAPEeGBX?usp=sharing

**Comment by Zeng-Jia** [comment]
> The preprocessed list is shared in the link below: https://drive.google.com/drive/folders/14pddCQBvlj43pxJJENi8pqp9YAPEeGBX?usp=sharing

Thank you for your sharing!
